export const TOGGLE_SHOW_HIDE = 'TOGGLE_SHOW_HIDE';
export const ADD_RETRO = 'ADD_RETRO';
export const ON_HANDLE_CHANGE = 'ON_HANDLE_CHANGE';
export const ADD_IMPROVE_RETRO = 'ADD_IMPROVE_RETRO';
export const ON_IMPROVE_CHANGE = 'ON_IMPROVE_CHANGE';
export const ON_SAVE_IMPROVE_CARD = 'ON_SAVE_IMPROVE_CARD';
export const ON_SHOW_EDIT_CARD = 'ON_SHOW_EDIT_CARD';